// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByiKzMd3MVINDwX2uGmH8AtjSfaIHZ8ss',
    appId: '1:722765495440:web:029306027443bef5c5ac15',
    messagingSenderId: '722765495440',
    projectId: 'nabtar-84e60',
    authDomain: 'nabtar-84e60.firebaseapp.com',
    storageBucket: 'nabtar-84e60.firebasestorage.app',
    measurementId: 'G-BBZG861T3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDitR-y4Nj4JH-KpM6cvGxPjnQkX_he2WY',
    appId: '1:722765495440:android:da37387d88b25ba1c5ac15',
    messagingSenderId: '722765495440',
    projectId: 'nabtar-84e60',
    storageBucket: 'nabtar-84e60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIiCPQEAZqNRyjUZiaoTL9ZXHeLJ7bG4g',
    appId: '1:722765495440:ios:28a1d3516b28cbb1c5ac15',
    messagingSenderId: '722765495440',
    projectId: 'nabtar-84e60',
    storageBucket: 'nabtar-84e60.firebasestorage.app',
    iosBundleId: 'com.example.nabtarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIiCPQEAZqNRyjUZiaoTL9ZXHeLJ7bG4g',
    appId: '1:722765495440:ios:28a1d3516b28cbb1c5ac15',
    messagingSenderId: '722765495440',
    projectId: 'nabtar-84e60',
    storageBucket: 'nabtar-84e60.firebasestorage.app',
    iosBundleId: 'com.example.nabtarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByiKzMd3MVINDwX2uGmH8AtjSfaIHZ8ss',
    appId: '1:722765495440:web:66eee312411003fec5ac15',
    messagingSenderId: '722765495440',
    projectId: 'nabtar-84e60',
    authDomain: 'nabtar-84e60.firebaseapp.com',
    storageBucket: 'nabtar-84e60.firebasestorage.app',
    measurementId: 'G-HE9PB7SBDM',
  );
}
