import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'register': 'Register',
      'register_title': 'Create Your Account',
      'register_desc': 'Sign up now to enjoy the best farming experience',
      'login': 'Login',
      'login_title': 'Go a head to Your Account',
      'login_desc':
          'Sign in now to your account to enjoy the best farming experience',
      'full_name': 'Full Name',
      'email': 'Email',
      'phone': 'Phone',
      'password': 'Password',
      'location': 'Location (City)',
      'remember_me': 'Remember Me',
      'forgot_password': 'Forgot Password?',
      'already_have_an_account': 'Already have an account? Login',
      "not_have_an_account": 'Don\'t have an account? Register',
      'or_login_with': 'Or login with',
      'google': 'Google',

      'hello': 'Hi,',
      'weather': "Today's weather in",
      'drone_title': "NABTAR Drones",
      'drone_desc':
          "Use drones to get accurate reports and comprehensive scans of your farm crop.",
      'drone_request': "Drone request",
      'articles': "Articles",
      'winter': "Winter",
      'spring': "Spring",
      'summer': "Summer",
      'article_1': "Plants that grow in the bitter cold!",
      'article_2': "Spring, the perfect season!",
      'article_3': "What can you grow in summer?",
      'more_know':
          "Learn more about the Nabtar app that combines AI and drone technologies to improve sustainable agriculture!",
      'soil_analysis_title': 'Soil Type Analysis',
      'no_image_selected': 'No image selected',
      'analysis_result': 'Analysis Result',
      'soil_type': 'Soil Type',
      'probability': 'Prediction Probability',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'confirm': 'Confirm',
      'choose_date': 'Choose from available dates',
      'farm_location': 'The registered farm location is being retrieved',
      'date_determining': 'Date determining',
      'signup_success': 'Signup Successful',
      'login_success': 'Login Successful',
      'logout_success': 'Logout Successful',
      'error': 'Error',
      'success': 'Success',
      'please_fill_all_fields': 'Please fill all fields',
      'please_enter_valid_email': 'Please enter a valid email',
      'password_length': 'Password length must be at least 6 ',
      'weather_info': 'Weather Information',
      'nitrogen': 'Nitrogen level(N)',
      'phosphorus': 'Phosphorus level(P)',
      'potassium': 'Potassium level(K)',
      'ph': 'PH of soil(ph)',
      'temperature': 'Temperature',
      'humidity': 'Local Humidity',
      'humidity_t': 'Humidity',
      'rainfall': 'Rainfall',
      'rainfall_per_season': 'Rainfall During the season',
      'no_data_found': 'No data found',
      'no_internet_connection': 'No internet connection',
      'no_data_available': 'No data available',
      'report': 'Report',
      'report_drone':'Drone Report',
      'scan_report': 'Scan Report on the Farm',
      'soil_analysis': 'Soil Analysis',
      'recommended_crops': 'Recommended Crops',
      'save': 'Save',
      'scan_date': 'Scan Date',
      'analyze_using_image': 'Analyze Soil Using Image',
      'analyze_using_drone': 'Analyze Soil Using Drone',
      'waiting': 'Waiting...',
      'home':'Home',
      'ml':'ML',
      'settings':'Settings',
      'profile':'Profile',
      'change_password':'Change Password',
      'about_us':'About Us',
      'privacy_policy':'Privacy Policy',
      'logout':'Logout',
      'my_reports':'Previous Scan Reports',
      'request_summary':'Request Summary',
      'scanning':'SCANNING...',
      'status':'Status',
      'progress':'Progress',
      'range':'Range',
      'reset_password':'Reset Password',
      'forgot_title':'Forgot Password',
      'forgot_sub':'Please enter your email to receive a link to reset your password.',
      'reset_link_sent_successfully':'Reset link sent successfully',
      'no_user_found_with_this_email':'No user found with this email.',


    },
    'ar': {
      'register': 'تسجيل',
      'register_title': 'سجل حسابك',
      'register_desc': 'سجل الآن للتمتع بأفضل تجربة زراعة',
      'login': 'دخول',
      'login_title': 'الدخول لحسابك',
      'login_desc': 'سجل دخولك الآن للتمتع بأفضل تجربة زراعة',
      'full_name': 'الاسم الكامل',
      'email': 'البريد الإلكتروني',
      'phone': 'رقم الهاتف',
      'password': 'كلمة المرور',
      'location': 'الموقع (المدينة)',
      'remember_me': 'تذكرنى',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'already_have_an_account': 'هل لديك حساب بالفعل؟ تسجيل الدخول',
      "not_have_an_account": 'ليس لديك حساب؟ سجل',
      'or_login_with': ' أو قم بتسجيل الدخول باستخدام',
      'google': 'جوجل',

      'hello': 'مرحبًا،',
      'weather': "طقس اليوم في ",
      'drone_title': "طائرات نابتر",
      'drone_desc':
          "استخدم الطائرات للحصول على تقارير دقيقة ومسح شامل لمحصول مزرعتك.",
      'drone_request': "طلب طائرة درون",
      'articles': "المقالات",
      'winter': "الشتاء",
      'spring': "الربيع",
      'summer': "الصيف",
      'article_1': "نباتات تنمو في البرد القارس!",
      'article_2': "الربيع، الموسم المثالي!",
      'article_3': "ماذا يمكنك أن تزرع في الصيف؟",
      'more_know':
          'تعرف أكثر على تطبيق نبتار الذي يدمج بين تقنيتي الذكاء الإصطناعي والدرونز في تحسين الزراعة المستدامة!',
      'soil_analysis_title': 'تحليل نوع التربة',
      'no_image_selected': ' لم يتم اختيار صورة',
      'analysis_result': 'نتيجة التحليل',
      'soil_type': 'نوع التربة',
      'probability': 'احتمالية التنبؤ',
      'gallery': 'معرض الصور',
      'camera': 'كاميرا',
      'confirm': 'تأكيد',
      'choose_date': 'اختر من التواريخ المتاحة',
      'farm_location': 'يتم استرجاع موقع المزرعة المسجلة',
      'date_determining': 'تحديد التاريخ',
      'signup_success': 'تم تسجيل الدخول بنجاح',
      'login_success': ' تم تسجيل الدخول بنجاح',
      'logout_success': ' تم تسجيل الخروج بنجاح',
      'error': 'خطأ',
      'success': 'تم',
      'please_fill_all_fields': 'الرجاء ملء جميع الحقول',
      'please_enter_valid_email': 'الرجاء إدخال بريد إلكتروني صالح',
      'password_length': ' يجب أن تكون طول كلمة المرور 6 على الأقل ',
      'weather_info': 'معلومات الطقس',
      'nitrogen': 'نسبة محتوى النيتروجين(N)في التربة',
      'phosphorus': 'نسبة محتوى الفوسفور(P) في التربة',
      'potassium': 'نسبة محتوى البوتاسيوم(K)في التربة',
      'ph': 'نسبة PH في التربة',
      'temperature': 'درجة الحرارة',
      'humidity': 'الرطوبة المحلية',
      'humidity_t': 'الرطوبة',
      'rainfall': 'هطول الأمطار',
      'rainfall_per_season': 'هطول الأمطار خلال الموسم',
      'no_data_found': 'لا توجد بيانات',
      'no_internet_connection': 'لا يوجد اتصال بالإنترنت',
      'no_data_available': 'لا توجد بيانات متاحة',
      'report': 'تقرير',
      'scan_report': 'تقرير المسح في المزرعة',
      'soil_analysis': 'تحليل التربة',
      'recommended_crops': 'المحاصيل الموصى بها',
      'save': 'حفظ',
      'scan_date': 'تاريخ المسح',
      'analyze_using_image': 'تحليل التربة باستخدام الصورة',
      'analyze_using_drone': 'تحليل التربة باستخدام الدرونز',
      'waiting': 'انتظر...',
      'home':'الرئيسية',
      'ml':'التحليل',
      'settings':'الإعدادات',
      'profile':' الملف الشخصي',
      'change_password':'تغيير كلمة المرور',
      'about_us':'حول التطبيق',
      'privacy_policy':'سياسة الخصوصية',
      'logout':'تسجيل الخروج',
      'report_drone':'تقرير الدرونز',
      'my_reports':'تقارير المسح السابقة',
      'request_summary':'ملخص الطلب',
      'scanning':'جاري المسح...',
      'status':'الحالة',
      'progress':'نسبة المسح',
      'range':'المدى',
      'reset_password':'إعادة تعيين كلمة المرور',
      'forgot_title':'نسيت كلمة المرور',
      'forgot_sub':'الرجاء إدخال بريدك الإلكتروني لتلقي رابط لتعيين كلمة المرور الجديدة.',
      'reset_link_sent_successfully':'تم ارسال رابط إعادة تعيين كلمة المرور بنجاح',
      'no_user_found_with_this_email':'لم يتم العثور على مستخدم بنفس البريد الإلكتروني هذا.',
    },
  };
}
